name: auto-redeploy
on:
  schedule:
    - cron: '50 * * * *'
jobs:
  build:
    name: daysredeploy
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Hook
        run: curl -X POST ${{ secrets.BUILD_HOOK }}
